### ISSUE TITLE
Could not find URI for JDK 18 on jdk.java.net

### ISSUE THREAD

**Issue by mpkorstanje** [oracle-actions/setup-java#12]
See [job#5259649098](https://github.com/junit-team/junit5/runs/5259649098) for https://github.com/junit-team/junit5/pull/2822

```
2022-02-19T16:25:42.2510544Z ##[error]Exception in thread "main" java.lang.Error: Could not find URI of JDK[release=18, version=latest, os=linux, arch=x64, type=tar.gz]
2022-02-19T16:25:42.2521433Z 	at Download.lambda$main$1(Download.java:72)
2022-02-19T16:25:42.2522291Z 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
2022-02-19T16:25:42.2522758Z 	at Download.main(Download.java:72)
2022-02-19T16:25:42.2523085Z 	at Download.main(Download.java:37)
2022-02-19T16:25:42.5813541Z ##[error]Process completed with exit code 1
```

@sormuras I'm guessing `jdk.java.net` changed the layout of the website somewhat.

**Comment by sormuras** [comment]
Thanks for reporting @mpkorstanje , looking into it...

**Comment by ottlinger** [comment]
At the moment I seem to be running into the same issue ..... shall I just reopen the bug or file a new one?

https://github.com/ottlinger/junit-mockito-examples/actions/runs/5690745880/job/15424671870

**Comment by sormuras** [comment]
As [JDK 18 has been superseded](https://jdk.java.net/18/), this is the expected behaviour.

The error message could hint to https://github.com/oracle-actions/setup-java#input-release, which has:
> Note also that websites may stop offering any release at any time. Please consult the website for details which release is offered for how long.

**Comment by ottlinger** [comment]
Ok, will migrate to a different GHA action as builds fail far too often. Thanks for the link/hint. In a multi-version scenario I intend to spot regressions, thus I want to build on "older" versions as well.
