### ISSUE TITLE
Q: Clarify why Java release 11 isn't available.

### ISSUE THREAD

**Issue by rbygrave** [oracle-actions/setup-java#14]
As per docs and testing the release version is 17 and up and does not include 11.

I'd just like to clarify why 11 is not available. Are there any plans to make 11 available?

That is, as a library author that has projects targeting Java release `11` I am effectively required to use Java `17` to build and test those projects (or use an alternate setup distribution). This seems less than optimal for those projects that are targeting 11.

```
Run JAVA=$JAVA_HOME_17_X64/bin/java
  JAVA=$JAVA_HOME_17_X64/bin/java
  DOWNLOAD=$GITHUB_ACTION_PATH/src/Download.java
  if [ ! -z "" ]; then
    $JAVA $DOWNLOAD 
  else
    $JAVA $DOWNLOAD oracle.com 11 latest
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Exception in thread "main" java.lang.Error: Could not find URI of JDK[release=11, version=latest, os=linux, arch=x64, type=tar.gz]
	at Download.lambda$main$1(Download.java:72)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at Download.main(Download.java:72)
	at Download.main(Download.java:37)
Error: Process completed with exit code 1.
```

**Comment by rbygrave** [comment]
I'm guessing this is down to licensing.  Would be keen to know for sure but ... closing

**Comment by delabassee** [comment]
re-opening the issue to make sure we document this.

**Comment by YaSuenag** [comment]
I think it is caused by [here](https://github.com/oracle-actions/setup-java/blob/main/src/Download.java) in Oracle JDK, and [here](https://github.com/oracle-actions/setup-java/blob/main/jdk.java.net-uri.properties) in jdk.java.net .

Do you have any plan to add earlier JDK release to them?

**Comment by sormuras** [comment]
> Do you have any plan to add earlier JDK release to them?

No. This action is about JDK 17 and higher.
