### ISSUE TITLE
JDK 22 does not seem to be available anymore

### ISSUE THREAD

**Issue by mbaumbach** [oracle-actions/setup-java#91]
Our JDK22 builds are failing today with the following error:

```
Run oracle-actions/setup-java@v1
Run echo "::group::Prepare download..."
Prepare download...
Exception in thread "main" java.lang.Error: Could not find URI of JDK[release=22, version=latest, os=linux, arch=x64, type=tar.gz]
	at Download.lambda$main$1(Download.java:[7](https://github.com/.../actions/runs/10920419179/job/30310225363#step:4:8)7)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at Download.main(Download.java:77)
	at Download.main(Download.java:42)
Error: Process completed with exit code 1.
```

I know JDK23 just came out, does that mean JDK22 is no longer available with this GitHub action?

**Comment by mbaumbach** [comment]
Can be ignored, it was due to the website being used.
